Pandas = data frames = excel chetao
Leer, limpiar filtrar, cruzar y stats de datos

In [1]:
import pandas as pd 

import kagglehub

# Download latest version
path = kagglehub.dataset_download("jasonqhiu/sp500")

print("Path to dataset files:", path)

df = pd.read_csv(f"{path}/GSPC.csv") #más rápido

/home/sergio/ApuntesQuant/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to /home/sergio/.cache/kagglehub/datasets/jasonqhiu/sp500/1.archive...

100%|██████████| 25.4k/25.4k [00:00<00:00, 15.1MB/s]

Extracting files...
Path to dataset files: /home/sergio/.cache/kagglehub/datasets/jasonqhiu/sp500/versions/1

Limpieza de datos

In [2]:
tablaBooleanaNan = df.isna() #Tabla si hay NaN o no
tablaBooleanaNan.sum() #sumatorio para dataframes
df.dropna() #Adios datos vacíos
df.fillna("Hola pana") #los NaN se le añade el valor puesto

,Date,Open,High,Low,Close,Adj Close,Volume,SPPerCh,SPYRChange
0,7/1/1954,29.209999,30.879999,29.209999,30.879999,30.879999,5.184000e+07,Hola pana,0.409326
1,8/1/1954,30.990000,31.209999,29.830000,29.830000,29.830000,5.690000e+07,-0.034003,0.447536
2,9/1/1954,30.040001,32.689999,30.040001,32.310001,32.310001,4.122000e+07,0.083138,0.351594
3,10/1/1954,32.290001,32.759998,31.680000,31.680000,31.680000,4.417000e+07,-0.019499,0.336490
4,11/1/1954,31.790001,34.549999,31.790001,34.240002,34.240002,6.301000e+07,0.080808,0.329147
...,...,...,...,...,...,...,...,...,...
772,11/1/2018,2717.580078,2815.149902,2631.090088,2760.169922,2760.169922,8.008011e+10,0.017859,-1.000000
773,12/1/2018,2790.500000,2800.179932,2346.580078,2506.850098,2506.850098,8.351957e+10,-0.091777,-1.000000
774,1/1/2019,2476.959961,2708.949951,2443.959961,2704.100098,2704.100098,8.039163e+10,0.078684,-1.000000
775,2/1/2019,2702.320068,2813.489990,2681.830078,2784.489990,2784.489990,7.018343e+10,0.029729,-1.000000
776,3/1/2019,2798.219971,2808.020020,2787.379883,2803.689941,2803.689941,3.972280e+09,0.006895,-1.000000

In [3]:
df.duplicated() #estan las filas duplicadas?
df.drop_duplicates() #adios filas duplicadas

,Date,Open,High,Low,Close,Adj Close,Volume,SPPerCh,SPYRChange
0,7/1/1954,29.209999,30.879999,29.209999,30.879999,30.879999,5.184000e+07,NaN,0.409326
1,8/1/1954,30.990000,31.209999,29.830000,29.830000,29.830000,5.690000e+07,-0.034003,0.447536
2,9/1/1954,30.040001,32.689999,30.040001,32.310001,32.310001,4.122000e+07,0.083138,0.351594
3,10/1/1954,32.290001,32.759998,31.680000,31.680000,31.680000,4.417000e+07,-0.019499,0.336490
4,11/1/1954,31.790001,34.549999,31.790001,34.240002,34.240002,6.301000e+07,0.080808,0.329147
...,...,...,...,...,...,...,...,...,...
772,11/1/2018,2717.580078,2815.149902,2631.090088,2760.169922,2760.169922,8.008011e+10,0.017859,-1.000000
773,12/1/2018,2790.500000,2800.179932,2346.580078,2506.850098,2506.850098,8.351957e+10,-0.091777,-1.000000
774,1/1/2019,2476.959961,2708.949951,2443.959961,2704.100098,2704.100098,8.039163e+10,0.078684,-1.000000
775,2/1/2019,2702.320068,2813.489990,2681.830078,2784.489990,2784.489990,7.018343e+10,0.029729,-1.000000
776,3/1/2019,2798.219971,2808.020020,2787.379883,2803.689941,2803.689941,3.972280e+09,0.006895,-1.000000

In [4]:
df['Date'].str.lower() #pasar a minúscula la columna entera
df['Date'].str.lower() #pasar a mayuscula la columna entera
df['Date'].str.strip() #quitar los espacios al principio y final
df['Date'].str.replace("/", ".") #cambiar los / por .

0       7.1.1954
1       8.1.1954
2       9.1.1954
3      10.1.1954
4      11.1.1954
         ...
772    11.1.2018
773    12.1.2018
774     1.1.2019
775     2.1.2019
776     3.1.2019
Name: Date, Length: 777, dtype: str

In [8]:
df.rename(columns={'Date': "Fecha_bro"}, inplace=True) #OJO: nombre viejo, nombre nuevo 
#OJO: inplace: reemplazo el nombre de la original o no?
df.replace (0, 1) #elementos se ponen como lo diga el tipo de dato
df["Fecha_bro"] = df["Fecha_bro"].astype(str)

Filtrar información

In [ ]:
a = df[df["Close"] > 100] #Se queda solo con los valores que cumplen o no
#Dentro debe haber una condición booleana, para el y -> & y para el o -> |
b = df[(df["Close"] > 100) & (df["Close"] < 200)] #Se queda solo con los valores que cumplen o no

datos = [100, 200, 300]
c = df[df["Close"].isin(datos)] #Se queda solo con los valores que están en la lista
d= df[df["Fecha_bro"].str.contains("2020", case=False, na=False)] #Se queda solo con los valores que contienen la cadena "2020" en la columna "Fecha_bro"
#Case indica si importa mayuscula o minuscula, na indica si se pueden los datos NaN

#OJO: mejor utilizar .query, mas limpio
p1 = 100
p2 = 200
df.query("Close > @p1 and Close < @p2") 
#Directamente se pone el nombre de las columnas y los operadores lógicos
#Se pone and y or en vez de & y |
#Para las variables, se pone @variable
u = df.query("Close in @p1")
v = df.query("Close not in @p1")
#eN VEZ DE USAR EL .isin() se puede usar el .query()
#OJO: si hay un espacio en medio, se pone `nombre de la columna`, son comillas invertidas
#OJO: cuidado si cambian muchos los valores

,Fecha_bro,Open,High,Low,Close,Adj Close,Volume,SPPerCh,SPYRChange
170,9/1/1968,98.860001,103.629997,98.309998,102.669998,102.669998,2.283000e+08,0.038539,-0.093016
171,10/1/1968,102.669998,105.779999,101.800003,103.410004,103.410004,2.722000e+08,0.007208,-0.060826
172,11/1/1968,103.410004,109.089996,101.849998,108.370003,108.370003,2.518500e+08,0.047964,-0.134355
173,12/1/1968,108.370003,109.370003,102.980003,103.860001,103.860001,2.674800e+08,-0.041617,-0.113615
174,1/1/1969,103.860001,104.870003,96.629997,103.010002,103.010002,2.666000e+08,-0.008184,-0.174643
...,...,...,...,...,...,...,...,...,...
371,6/1/1985,189.550003,191.850006,185.029999,191.850006,191.850006,2.117000e+09,0.012134,0.307480
372,7/1/1985,191.850006,196.070007,189.300003,190.919998,190.919998,2.463070e+09,-0.004848,0.236748
373,8/1/1985,190.919998,192.169998,186.100006,188.630005,188.630005,1.923200e+09,-0.011995,0.340879
374,9/1/1985,188.630005,188.800003,179.449997,182.080002,182.080002,1.860160e+09,-0.034724,0.270431
375,10/1/1985,182.059998,190.149994,181.160004,189.820007,189.820007,2.543240e+09,0.042509,0.285323

Operaciones avanzadas

In [ ]:
c = pd.concat([a, b]) #Concatenar dos dataframes
print(c.head()) #Ver la cabeza

d = pd.merge(a, b, on="Fecha_bro", how="inner") #Datos en común que junta para crear un nuevo dataframe
print(d.head()) #Ver la cabeza
#Inner: solo intersección común ambos, left: todo izquierda, right: todo derecha, outer: todo los datos

     Fecha_bro        Open        High         Low       Close   Adj Close  \
170   9/1/1968   98.860001  103.629997   98.309998  102.669998  102.669998
171  10/1/1968  102.669998  105.779999  101.800003  103.410004  103.410004
172  11/1/1968  103.410004  109.089996  101.849998  108.370003  108.370003
173  12/1/1968  108.370003  109.370003  102.980003  103.860001  103.860001
174   1/1/1969  103.860001  104.870003   96.629997  103.010002  103.010002

          Volume   SPPerCh  SPYRChange
170  228300000.0  0.038539   -0.093016
171  272200000.0  0.007208   -0.060826
172  251850000.0  0.047964   -0.134355
173  267480000.0 -0.041617   -0.113615
174  266600000.0 -0.008184   -0.174643
   Fecha_bro      Open_x      High_x       Low_x     Close_x  Adj Close_x  \
0   9/1/1968   98.860001  103.629997   98.309998  102.669998   102.669998
1  10/1/1968  102.669998  105.779999  101.800003  103.410004   103.410004
2  11/1/1968  103.410004  109.089996  101.849998  108.370003   108.370003
3  12/1/1968  108.370003  109.370003  102.980003  103.860001   103.860001
4   1/1/1969  103.860001  104.870003   96.629997  103.010002   103.010002

      Volume_x  SPPerCh_x  SPYRChange_x      Open_y      High_y       Low_y  \
0  228300000.0   0.038539     -0.093016   98.860001  103.629997   98.309998
1  272200000.0   0.007208     -0.060826  102.669998  105.779999  101.800003
2  251850000.0   0.047964     -0.134355  103.410004  109.089996  101.849998
3  267480000.0  -0.041617     -0.113615  108.370003  109.370003  102.980003
4  266600000.0  -0.008184     -0.174643  103.860001  104.870003   96.629997

      Close_y  Adj Close_y     Volume_y  SPPerCh_y  SPYRChange_y
0  102.669998   102.669998  228300000.0   0.038539     -0.093016
1  103.410004   103.410004  272200000.0   0.007208     -0.060826
2  108.370003   108.370003  251850000.0   0.047964     -0.134355
3  103.860001   103.860001  267480000.0  -0.041617     -0.113615
4  103.010002   103.010002  266600000.0  -0.008184     -0.174643

In [ ]:
d = a.groupby("Fecha_bro").sum() #Ojo, se agrupa, se selecciona la columna y se palica una operación

Operaciones aritmeticas

In [ ]:
print(a.sum())
print(a.mean())
print(a.median())
print(a.max())
print(a.min())
print(a.count()) #Contar elementos
print(a.describe()) #Resumen estadístico

Fecha_bro     9/1/196810/1/196811/1/196812/1/19681/1/19693/1...
Open                                              457923.798757
High                                              472473.110652
Low                                               442855.779909
Close                                             460495.289778
Adj Close                                         460495.289778
Volume                                         16117056860000.0
SPPerCh                                                4.438499
SPYRChange                                            30.478364
dtype: object

TypeError: Cannot perform reduction 'mean' with string dtype